server:
  port: 5001


spring:
  application:
    name: zuul-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

zuul:
  routes: #代理的routes
    user.serviceId: user-provider
    user.path: /sys/*
  ignored-services: "*" #忽略原真实服务名
  prefix: /rancho #统一前缀
